FROM nginx

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration files
COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d/
COPY ./docker/nginx/error.conf /etc/nginx/

# Expose port 80 for Nginx
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
